export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: "user/SET_CURRENT_USER",
    SET_IS_CLIENT_AUTHENTICATED: "user/SET_IS_CLIENT_AUTHENTICATED",
    SET_IS_FUNC_AUTHENTICATED: "user/SET_IS_FUNC_AUTHENTICATED",
};